### ISSUE TITLE
Localhost => $(boot2docker ip)

### ISSUE THREAD

**Issue by hunterloftis** [hunterloftis/docker-plugin#5]
Don't map localhost:3000 to vbox / boot2docker.

Instead, heroku docker:open should dynamically look up boot2docker's ip and exposed port and then open it up.

Problem: this tightly couples to boot2docker, which we were trying to avoid. Is there any other way?

**Comment by friism** [comment]
@hunterloftis `DOCKER_IP`? https://www.google.com/search?q=boot2docker+%22docker_ip%22

**Comment by hunterloftis** [comment]
@friism you mean telling the user to add something to their bash profile like `export DOCKER_IP=whatever method you want`?

**Comment by hunterloftis** [comment]
Looks like `$DOCKER_HOST` will work fine.
