### ISSUE TITLE
Split node-specific stuff into modules

### ISSUE THREAD

**Issue by hunterloftis** [hunterloftis/docker-plugin#6]
eg:

```
heroku docker:create --node
```

**Comment by friism** [comment]
Couldn't we have `detect` like functionality that did this? /cc @tt

**Comment by hunterloftis** [comment]
@friism how would that work with blank-slate projects? Keep in mind we're assuming they don't have a local dev environment & we're providing that original dev environment in docker:

```
$ ls # empty dir
$ heroku docker:create # what happens now?
```

**Comment by friism** [comment]
True, we should absolutely also provide the option of a flag like you're proposing

**Comment by hunterloftis** [comment]
@friism what do you think of something like this?
1. Is there an explicit flag like `--node` or `--ruby`? If so, use the template associated with that flag.
2. Is there a `Dockerfile` in `.`? If so, create an image based on that `Dockerfile`
3. Run through all available `detect` scripts. If any match, use the template associated with the match.
4. Insufficient info to create an image - show an error.

**Comment by friism** [comment]
sounds perfect

**Comment by hunterloftis** [comment]
Related to https://github.com/hunterloftis/docker-plugin/issues/3

**Comment by tt** [comment]
I think we could punt on the explicit flag. It's just a matter of creating something that qualifies and then run the command; you'll need to do that anyway.

A thought on the command naming: I feel `init` works better and especially when the Dockerfile stays. The operation is more like `git init` than `heroku create`.

**Comment by hunterloftis** [comment]
Addressed with https://github.com/hunterloftis/docker-plugin/pull/10

**Comment by hunterloftis** [comment]
@tt the `Dockerfile` part of `docker:create` maps well to `git init` but creating the runnable image used by `docker:run` maps better to `heroku create`. The next docker meeting is on Friday so let's chat about it then.
